export { default as Empty } from './empty.svg?react';
export { default as Loading } from './loading.svg?react';
export { default as Delete } from './delete.svg?react';
// export { default as Group } from './group2.svg?react';
export { default as Group } from './group.svg?react';
export { default as Users } from './users.svg?react';
export { default as Plan } from './plan.svg?react';
export { default as Document } from './document.svg?react';
export { default as DateSvg } from './date.svg?react';
export { default as Leaderboard } from './leaderboard.svg?react';
export { default as TavanbogdLogo } from './TavanbogdLogo.svg?react';
export { default as ReportSVG } from './report.svg?react';
export { default as QuestionsSVG } from './questions.svg?react';
